version: '3.8'

services:
  server:
    build:
      target: ${NODE_ENV}
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /home/aryan/judge0:/app/judge0
      - /home/aryan/judge0/config/serviceAccount.js:/app/judge0/config/serviceAccount.js
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
